# docker run --rm --name via-gotur -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=gotur mysql  --secure-file-priv=/home/barisozgen/development/personal/via/via-505/via-505-final/data --local-infile=1
version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: gotur_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gotur
    command:
      - "--secure-file-priv=/home/barisozgen/development/personal/via/via-505/via-505-final/data"
      - "--local-infile=1"


    