version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: gotur_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gotur
    command:
      - "--secure-file-priv=./data"
      - "--local-infile=1"


    